name: CI/CD Pipeline (Auto Node App)

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install
    - run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v3
    - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/auto-nodejs-app:latest .

  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3
    - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - run: docker push ${{ secrets.DOCKER_USERNAME }}/auto-nodejs-app:latest
